### ISSUE TITLE
JSON payload not being parsed correctly on Windows Shell

### ISSUE THREAD

**Issue by mrkevinze** [GoogleCloudPlatform/cloud-functions-emulator#90]
### Description
Specifying an inline JSON payload will not work on a Windows shell if one follows the recommended CLI usage pattern. An error 

> "data" must be a valid JSON string!

 is emitted.

The recommended CLI usage is
`functions call helloWorld --data='{"foo":"bar"}'`

The recommended command works fine when using [Git Bash](https://git-scm.com/) on Windows. However, it does not work when using the Google Cloud SDK Shell on Windows nor on the Windows Command Prompt; the aforementioned error will be thrown.

To see how the JSON is parsed, add `console.log(process.argv);` in the file /bin/functions. It becomes '\'{foo:bar}\'' which is indeed not valid JSON. It should be '{"foo":"bar"}' instead.

This problem may be related to #34 , but the problem is for `call` rather than `deploy`.

### Steps to reproduce
Invoke `functions call helloWorld --data='{"foo":"bar"}'` using the Google Cloud SDK Shell on Windows or using the Windows Command Prompt.

### Workaround
When using a Windows shell, call `functions call helloWorld --data={\"foo\":\"bar\"}` instead.
Note that this workaround is not compatible with Bash on Windows.

Thanks!

**Comment by jmdobry** [comment]
I've updated [the docs](https://github.com/GoogleCloudPlatform/cloud-functions-emulator/wiki/Calling-functions) and the [CLI's help text](https://github.com/GoogleCloudPlatform/cloud-functions-emulator/commit/aa2a5cc4bbe898bee43b3f99fa8b25f04215e16d) with Windows-specific instructions.

**Comment by kmleow** [comment]
I have tried the backslash workaround, does not work. This is what I see with 1.0 alpha 25:
Error: "data" must be a valid JSON string!

**Comment by jmdobry** [comment]
So on windows the surrounding single quotes are what made it work for you?

**Comment by kmleow** [comment]
@jmdobry yes, without equal (=) sign

**Comment by jmdobry** [comment]
I updated the docs, thanks.

**Comment by rijuvan** [comment]
HI 

It is still not working and I ma getting below error 

D:\gcp_demo\functionTraining\http>functions call helloWorld --data '{\"message\":\"Hello, World\"}'
Error: "data" must be a valid JSON string!
    at Object.exports.handler.err [as handler] (C:\Users\Rijuvan.Ansari\AppData\Roaming\npm\node_mod
ules\@google-cloud\functions-emulator\src\cli\commands\call.js:76:13)
    at Object.runCommand (C:\Users\Rijuvan.Ansari\AppData\Roaming\npm\node_modules\@google-cloud\fun
ctions-emulator\node_modules\yargs\lib\command.js:235:44)
    at Object.parseArgs [as _parseArgs] (C:\Users\Rijuvan.Ansari\AppData\Roaming\npm\node_modules\@g
oogle-cloud\functions-emulator\node_modules\yargs\yargs.js:1014:30)
    at Object.parse (C:\Users\Rijuvan.Ansari\AppData\Roaming\npm\node_modules\@google-cloud\function
s-emulator\node_modules\yargs\yargs.js:542:25)
    at Object.main (C:\Users\Rijuvan.Ansari\AppData\Roaming\npm\node_modules\@google-cloud\functions
-emulator\src\cli\main.js:69:6)
    at getProjectId.then (C:\Users\Rijuvan.Ansari\AppData\Roaming\npm\node_modules\@google-cloud\fun
ctions-emulator\bin\functions:104:27)
    at process._tickCallback (internal/process/next_tick.js:109:7)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:383:7)
    at startup (bootstrap_node.js:149:9)

Thanks in Advance !!

**Comment by chrisbeech** [comment]
It doesn't like the wrapping single quotes for me. This works:
`functions call helloWorld --data "{\"message\":\"Hello World\"}"`
